### PR TITLE
Azumi Logo

### PR DESCRIPTION
**Pull request by TYP3D**
-Png File of azumis logo
-(New Blurple)

Signed-off-by: TYP3D <114131693+TYP3D@users.noreply.github.com>

### CODE REVIEW

**Comment by AquaQuokka** [comment]
Still can't see it lol

**Comment by AquaQuokka** [comment]
Oh nvm now i can

**Review by AquaQuokka — CHANGES_REQUESTED** [review]
Just one thing. Can you change the file name to "azumi.png"?

**Comment by TYP3D** [comment]
uhh i cant do that i dont think, cant you?

**Pull request closed without merging**
